
## Generate simulated clusters

# The following example data set has nested clusters. The data are generated by simulating a J = 240 dimensional vector consisting of eight groups of thirty normally distributed variables with the following means: µ = (1,2,5,6,14,15,18,19). The variables are uncorrelated with common standard deviation s = 0.5. A sample of I = 25 is generated and the Euclidean distance computed.

k = 8

mu <- c(1, 2, 5, 6, 14, 15, 18, 19)
X <- matrix(rnorm(240 * 25, 0, 0.5), nrow = 240, ncol = 25)
step <- 240/length(mu)
for (m in 1:length(mu)) X[((m - 1) * step + 1):(m * step), ] <- X[((m - 1) * step + 1):(m * step), ] + mu[m]
D <- dist(X, method = "euclidean")

write.table(X, "data-matrix.txt", row.names=FALSE, col.names=FALSE, sep="\t")
write.table(as.matrix(D), "distance-matrix.txt", row.names=FALSE, col.names=FALSE, sep="\t")


## Cluster with HOPACH

require(hopach)
h <- hopach(X, dmat = D, clusters = "best", K = 15, col = "seq", mss = "med", initord = "co", ord = "neighbor")
write.table(h$clustering$labels, "hopach.txt", row.names=FALSE, col.names=FALSE, sep="\t")
saveRDS(h, "hopach.rds")


## Cluster with PAM

require(pam)
p <- pam(D, k)
write.table(p$clustering, "pam.txt", row.names=FALSE, col.names=FALSE, sep="\t")
saveRDS(p, "pam.rds")
